### ISSUE TITLE
Template rendering with pod structure

### ISSUE THREAD

**Issue by dguettler** [mitchlloyd/ember-islands#19] opened 2016-02-08 20:24 UTC
When trying to use pod structure component templates are rendered empty.
The component is looked up correctly within ember-island, but the template seems to be missing.
I confirmed that the same component renders correctly when served via `ember serve` and included directly in the `application.hbs` template.

**Comment by mitchlloyd** [comment] 2016-02-08 22:12
I'm suspicious that Ember's `componentLookup` may not be resolving these templates. Need to investigate how component lookup works in an Ember CLI app using PODs.

**Comment by mitchlloyd** [comment] 2016-02-09 02:35
I couldn't reproduce with with Ember `~2.1.0` and `~2.3.0` and I couldn't. Is it possible you're using a more bleeding edge Ember? If so, I'm a little wary of making changes for unreleased Ember versions... especially for features like pods that are still undergoing lots of churn.

Otherwise, let me know what Ember version you're using. If you have a public repo to reproduce that would be even better!

**Comment by mitchlloyd** [comment] 2016-02-09 03:41
@dguettler and I were able to debug over Slack. For now the `componentLookup` technique remains strong, it appears to be working with POD organizations in Ember 2.3.x.

**Closed by mitchlloyd** 2016-02-09 03:41 UTC
